export { default as Welcome } from './Welcome'
export { default as Nav } from './Nav'
export { default as About } from './About'
export { default as Experience } from './Experience'
export { default as Services } from './Services'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'